
package com.sixdee.imp.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PointManagement", targetNamespace = "http://service.imp.sixdee.com", wsdlLocation = "http://10.0.0.95:8095/LMS/services/PointManagement?wsdl")
public class PointManagement
    extends Service
{

    private final static URL POINTMANAGEMENT_WSDL_LOCATION;
    private final static WebServiceException POINTMANAGEMENT_EXCEPTION;
    private final static QName POINTMANAGEMENT_QNAME = new QName("http://service.imp.sixdee.com", "PointManagement");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.0.0.95:8095/LMS/services/PointManagement?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        POINTMANAGEMENT_WSDL_LOCATION = url;
        POINTMANAGEMENT_EXCEPTION = e;
    }

    public PointManagement() {
        super(__getWsdlLocation(), POINTMANAGEMENT_QNAME);
    }

    public PointManagement(WebServiceFeature... features) {
        super(__getWsdlLocation(), POINTMANAGEMENT_QNAME, features);
    }

    public PointManagement(URL wsdlLocation) {
        super(wsdlLocation, POINTMANAGEMENT_QNAME);
    }

    public PointManagement(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POINTMANAGEMENT_QNAME, features);
    }

    public PointManagement(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PointManagement(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PointManagementPortType
     */
    @WebEndpoint(name = "PointManagementHttpSoap11Endpoint")
    public PointManagementPortType getPointManagementHttpSoap11Endpoint() {
        return super.getPort(new QName("http://service.imp.sixdee.com", "PointManagementHttpSoap11Endpoint"), PointManagementPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PointManagementPortType
     */
    @WebEndpoint(name = "PointManagementHttpSoap11Endpoint")
    public PointManagementPortType getPointManagementHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.imp.sixdee.com", "PointManagementHttpSoap11Endpoint"), PointManagementPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POINTMANAGEMENT_EXCEPTION!= null) {
            throw POINTMANAGEMENT_EXCEPTION;
        }
        return POINTMANAGEMENT_WSDL_LOCATION;
    }

}
